apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 22.3.2      # example version
    chart: nginx
    helm:
      valueFiles:
        - '../../envs/prod/nginx.values.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
